version: '3.8'
services:
  db:
    image: mysql:8.0.36
    environment:
      MYSQL_DATABASE: 'project2_db'
      MYSQL_USER: 'ubuntu'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_HOST: db
