apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # encoded 'password'
  MYSQL_DATABASE: cHJvamVjdDJfZGI=      # encoded 'project2_db'
  MYSQL_USER: dWJ1bnR1                # encoded 'ubuntu'
  MYSQL_PASSWORD: cGFzc3dvcmQ=        # encoded 'password'
