apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: katekar/todo-app:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: "mysql-service"
        - name: DATABASE_NAME
          value: "project2_db"
        - name: DATABASE_USER
          value: "ubuntu"
        - name: DATABASE_PASSWORD
          value: "password"
        - name: DATABASE_PORT
          value: "3306"
