replicaCount: 2

image:
  repository: katekar/todo-app
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: NodePort
  port: 8000
  nodePort: 30002

env:
  DATABASE_HOST: mysql-service
  DATABASE_NAME: project2_db
  DATABASE_USER: ubuntu
  DATABASE_PASSWORD: password

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false  
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []  


autoscaling:
  enabled: false  
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

