apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "todo-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "todo-app.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: DATABASE_HOST
              value: {{ .Values.env.DATABASE_HOST }}
            - name: DATABASE_NAME
              value: {{ .Values.env.DATABASE_NAME }}
            - name: DATABASE_USER
              value: {{ .Values.env.DATABASE_USER }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.env.DATABASE_PASSWORD }}
